<div class="indexContenaire">
    <div class="indexContenaireIntro">

    <h1>Habibiatore</h1>

    <p>l'Akinator des planètes ! Rejoignez Habibiatore pour redécouvrir le system solaire à travers des questions simples !</p>
    <a href="login.php" class="button">Log-in</a>
    <a href="signup.php" class="button">Signup</a>
    </div>
    <img class="right" src="image/color-scheme-right.svg">
    <img class="left" src="image/color-scheme-left.svg">
</div>