<h2>Account</h2>
<section>
    <section>
        <?= $_SESSION['user'] ?><br>
        <?= $username_email['email'] ?><br>
        <a href="delete.php">Delete my account</a>

        <form method="POST">
            <h3>New task</h3>
            
            <label for="Title">Title</label>
            <input type="text" id="Title" name="Title" required>
            
            <label for="Content">Content :</label>
            <input type="text" id="Content" name="Content" required>
            
            <p>Urgent</p>
            <label class="switch" for="Urgent">
                <input type="checkbox" id="Urgent" name="Urgent">
                <span class="slider"></span>
            </label>

            <p>Important</p>
            <label class="switch" for="Important">
                <input type="checkbox" id="Important" name="Important">
                <span class="slider"></span>
            </label>
            
            <button type="submit">Add</button>
        </form>
    </section>
    
    <section>
        <h2>Vos tâches</h2>
        <ul>
    <?php foreach ($tasks as $task): ?>
        <li>
            <strong><?php echo htmlspecialchars($task['name_task']); ?></strong>
            <p><?php echo htmlspecialchars($task['description_task']); ?></p>
            <p>
                <?php echo $task['urgent_task'] ? 'Urgent' : 'Pas urgent'; ?> - 
                <?php echo $task['important_task'] ? 'Important' : 'Pas important'; ?>
            </p>
            <?php if (isset($task['id_task'])): ?>
                <a href="task.php?id=<?php echo $task['id_task']; ?>">Voir la tâche</a>
                <a href="deleteTask.php?id=<?php echo $task['id_task']; ?>">Suprimer La tache</a>
            <?php else: ?>
                <p>ID de tâche non fourni.</p>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>

    </section>


</section>